FROM python:3.11-alpine

WORKDIR /app

COPY extensions/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY extensions/merge-freeze/merge-freeze-server.py .

EXPOSE 8081

CMD ["python", "merge-freeze-server.py"]
