FROM python:3.11-alpine

WORKDIR /app

COPY extensions/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY extensions/incident-timer/incident-timer-server.py .

EXPOSE 8088

CMD ["python", "incident-timer-server.py"]
