server:
  assets-path: /app/assets
  port: 8085

theme:
  background-color: 220 5 10
  primary-color: 132 100 47
  negative-color: 358 72 52
  contrast-multiplier: 1.4

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
