- name: Home
  width: wide
  head-widgets:
    - type: group
      title: GitHub Activity
      widgets:
        - type: html
          title: Quick Links
          content: |
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
              <a href="https://github.com/notifications" target="_blank" 
                 style="background: #21262d; color: #f0f6fc; padding: 8px; text-decoration: none; border-radius: 4px; display: block; text-align: center; font-size: 0.9em;">
                üì¨ Notifications
              </a>
              <a href="https://github.com/pulls/assigned" target="_blank" 
                 style="background: #21262d; color: #f0f6fc; padding: 8px; text-decoration: none; border-radius: 4px; display: block; text-align: center; font-size: 0.9em;">
                üîç PR Reviews
              </a>
            </div>
    - type: split-column
      max-columns: 6
  columns:
    - size: small
      widgets:
        - type: repository
          repository: PlayerData/api
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/app
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/web
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/analysis-services
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/playerdata-core
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
    - size: full
      widgets:
        - type: split-column
          max-columns: 2
          widgets:
            - type: custom-api
              title: üö® PagerDuty Incidents
              cache: 2m
              hide-header: false
              url: https://api.pagerduty.com/incidents?total=false&time_zone=UTC&statuses%5B%5D=triggered
              headers:
                accept: application/vnd.pagerduty+json;version=2
                content-type: application/json
                authorization: Token token=${PAGER_KEY}
              template: |
                {{ $incidents := .JSON.Array "incidents" }}
                {{ if $incidents }}
                  {{ range $incidents }}
                    <div class="margin-block-1">
                      <a href="{{ .String "html_url" }}" class="color-negative size-h4" style="text-decoration: none;">
                        üî¥ {{ .String "title" }}
                      </a>
                      <div class="size-h6 color-subtext">
                        {{ .String "service.summary" }}
                      </div>
                    </div>
                  {{ end }}
                {{ else }}
                  <div class="color-positive size-h4">‚úÖ No Active Incidents</div>
                {{ end }}
            - type: custom-api
              title: üë• On-Call Schedule
              cache: 5m
              hide-header: false
              url: https://api.pagerduty.com/oncalls?total=false&time_zone=UTC&escalation_policy_ids%5B%5D=PLEBQTR
              headers:
                accept: application/vnd.pagerduty+json;version=2
                content-type: application/json
                authorization: Token token=${PAGER_KEY}
              template: |
                {{ $oncalls := .JSON.Array "oncalls" }}
                {{ if $oncalls }}
                  {{ range $oncalls }}
                    {{ if eq (.Int "escalation_level") 1 }}
                      <div class="margin-block-1">
                        <div class="color-primary size-h4">
                          1Ô∏è‚É£ {{ .String "user.summary" }}
                        </div>
                        <div class="size-h6 color-subtext">Primary On-Call</div>
                      </div>
                    {{ end }}
                  {{ end }}
                  {{ range $oncalls }}
                    {{ if eq (.Int "escalation_level") 2 }}
                      <div class="margin-block-1">
                        <div class="color-secondary size-h5">
                          2Ô∏è‚É£ {{ .String "user.summary" }}
                        </div>
                        <div class="size-h6 color-subtext">Level 2 Escalation</div>
                      </div>
                    {{ end }}
                  {{ end }}
                {{ else }}
                  <div class="color-subtext size-h5">No On-Call Data</div>
                {{ end }}
        - type: rss
          title: üìã My Open Pull Requests
          limit: 10
          cache: 1m
          feeds:
            - url: http://github-pr-scraper:8086/my-open-prs.xml
              title: My PRs
        - type: repository
          repository: PlayerData/roadmap
          token: ${GITHUB_KEY}
          pull-requests-limit: -1
          issues-limit: 10
          hide-header: true
    - size: small
      widgets:
        - type: bookmarks
          hide-header: true
          groups:
            - links:
                - title: PlayerData
                  url: https://app.playerdata.co.uk
                - title: Argo
                  url: https://argocd.playerdata.co.uk/applications
                - title: Grafana
                  url: https://grafana.playerdata.co.uk/d/86ckrLFnz/monday-dashboard?orgId=1
                - title: Figma
                  url: https://www.figma.com/files
                - title: Sentry
                  url: https://sentry.io/organizations/playerdata-ltd/projects/
                - title: Cloud Logs
                  url: https://console.cloud.google.com/logs/query?project=playerdata-infrastructure-prod
        - type: extension
          url: http://merge-freeze-extension:8081
          cache: 2m
          allow-potentially-dangerous-html: true
        - type: weather
          location: Chorley, United Kingdom
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: custom-api
          title: Air Quality
          cache: 10m
          hide-header: true
          url: https://api.waqi.info/feed/geo:53.6535;2.6326/?token=${AQI_KEY}
          template: |
            {{ $aqi := printf "%03s" (.JSON.String "data.aqi") }}
            {{ $aqiraw := .JSON.String "data.aqi" }}
            {{ $updated := .JSON.String "data.time.iso" }}
            {{ $humidity := .JSON.String "data.iaqi.h.v" }}
            {{ $ozone := .JSON.String "data.iaqi.o3.v" }}
            {{ $pm25 := .JSON.String "data.iaqi.pm25.v" }}
            {{ $pressure := .JSON.String "data.iaqi.p.v" }}

            <div class="flex justify-between">
              <div class="size-h5">
                {{ if le $aqi "050" }}
                  <div class="color-positive">Good air quality</div>
                {{ else if le $aqi "100" }}
                  <div class="color-primary">Moderate air quality</div>
                {{ else }}
                  <div class="color-negative">Bad air quality</div>
                {{ end }}
              </div>
            </div>

            <div class="color-highlight size-h2">AQI: {{ $aqiraw }}</div>
            <div style="border-bottom: 1px solid; margin-block: 10px;"></div>

            <div class="margin-block-2">
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">

                <div>
                  <div class="size-h3 color-highlight">{{ $humidity }}%</div>
                  <div class="size-h6">HUMIDITY</div>
                </div>

                <div>
                  <div class="size-h3 color-highlight">{{ $ozone }} Œºg/m¬≥</div>
                  <div class="size-h6">OZONE</div>
                </div>

                <div>
                  <div class="size-h3 color-highlight">{{ $pm25 }} Œºg/m¬≥</div>
                  <div class="size-h6">PM2.5</div>
                </div>

                <div>
                  <div class="size-h3 color-highlight">{{ $pressure }} hPa</div>
                  <div class="size-h6">PRESSURE</div>
                </div>

              </div>

              <div class="size-h6" style="margin-top: 10px;">Last Updated at {{ slice $updated 11 16 }}</div>
            </div>
        - type: calendar
          first-day-of-week: monday
