- name: Home
  width: wide
  columns:
    - size: small
      widgets:
        - type: repository
          repository: PlayerData/api
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/app
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/web
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/analysis-services
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
        - type: repository
          repository: PlayerData/playerdata-core
          token: ${GITHUB_KEY}
          pull-requests-limit: 2
          issues-limit: 2
          hide-header: true
    - size: full
      widgets:
        - type: split-column
          max-columns: 2
          widgets:
            - type: custom-api
              title: 🚨 PagerDuty Incidents
              cache: 2m
              hide-header: false
              url: https://api.pagerduty.com/incidents?total=false&time_zone=UTC&statuses%5B%5D=triggered
              headers:
                accept: application/vnd.pagerduty+json;version=2
                content-type: application/json
                authorization: Token token=${PAGER_KEY}
              template: |
                {{ $incidents := .JSON.Array "incidents" }}
                {{ if $incidents }}
                  {{ range $incidents }}
                    <div class="margin-block-1">
                      <a href="{{ .String "html_url" }}" class="color-negative size-h4" style="text-decoration: none;">
                        🔴 {{ .String "title" }}
                      </a>
                      <div class="size-h6 color-subtext">
                        {{ .String "service.summary" }}
                      </div>
                    </div>
                  {{ end }}
                {{ else }}
                  <div class="color-positive size-h4">✅ No Active Incidents</div>
                {{ end }}
            - type: custom-api
              title: 👥 On-Call Schedule
              cache: 5m
              hide-header: false
              url: https://api.pagerduty.com/oncalls?total=false&time_zone=UTC&escalation_policy_ids%5B%5D=PLEBQTR
              headers:
                accept: application/vnd.pagerduty+json;version=2
                content-type: application/json
                authorization: Token token=${PAGER_KEY}
              template: |
                {{ $oncalls := .JSON.Array "oncalls" }}
                {{ if $oncalls }}
                  {{ range $oncalls }}
                    {{ if eq (.Int "escalation_level") 1 }}
                      <div class="margin-block-1">
                        <div class="color-primary size-h4">
                          1️⃣ {{ .String "user.summary" }}
                        </div>
                        <div class="size-h6 color-subtext">Primary On-Call</div>
                      </div>
                    {{ end }}
                  {{ end }}
                  {{ range $oncalls }}
                    {{ if eq (.Int "escalation_level") 2 }}
                      <div class="margin-block-1">
                        <div class="color-secondary size-h5">
                          2️⃣ {{ .String "user.summary" }}
                        </div>
                        <div class="size-h6 color-subtext">Level 2 Escalation</div>
                      </div>
                    {{ end }}
                  {{ end }}
                {{ else }}
                  <div class="color-subtext size-h5">No On-Call Data</div>
                {{ end }}
        - type: split-column
          max-columns: 2
          widgets:
            - type: rss
              title: 📝 My Open Pull Requests
              limit: 10
              cache: 1m
              feeds:
                - url: http://github-pr-scraper:8086/my-open-prs.xml
                  title: Authored by Me
            - type: rss
              title: 👀 PRs to Review
              limit: 10
              cache: 1m
              feeds:
                - url: http://github-pr-scraper:8086/assigned-prs.xml
                  title: Assigned to Me
        - type: repository
          repository: PlayerData/roadmap
          token: ${GITHUB_KEY}
          pull-requests-limit: -1
          issues-limit: 10
          hide-header: true
    - size: small
      widgets:
        - type: bookmarks
          hide-header: true
          groups:
            - links:
                - title: PlayerData
                  url: https://app.playerdata.co.uk
                - title: Argo
                  url: https://argocd.playerdata.co.uk/applications
                - title: Grafana
                  url: https://grafana.playerdata.co.uk/d/86ckrLFnz/monday-dashboard?orgId=1
                - title: Figma
                  url: https://www.figma.com/files
                - title: Sentry
                  url: https://sentry.io/organizations/playerdata-ltd/projects/
                - title: Cloud Logs
                  url: https://console.cloud.google.com/logs/query?project=playerdata-infrastructure-prod
        - type: extension
          title: ❄️ Merge Freeze Status
          url: http://merge-freeze-extension:8081
          cache: 10m
          allow-potentially-dangerous-html: true
