services:
  glance:
    image: glanceapp/glance:latest
    ports:
      - "8085:8085"
    depends_on:
      - merge-freeze-extension
    volumes:
      - ./config:/app/config:ro
      - ./assets:/app/assets:ro
    environment:
      - GLANCE_CONFIG=/app/config/home.yml
      - GITHUB_KEY=${GITHUB_KEY}
      - PAGER_KEY=${PAGER_KEY}
      - AQI_KEY=${AQI_KEY}
      - MERGE_APP_KEY=${MERGE_APP_KEY}
    networks:
      - glance-network

  merge-freeze-extension:
    build:
      context: .
      dockerfile: Dockerfile.extension
    ports:
      - "8081:8081"
    environment:
      - MERGE_APP_KEY=${MERGE_APP_KEY}
      - GITHUB_KEY=${GITHUB_KEY}
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8081/health')",
        ]
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s
    networks:
      - glance-network

networks:
  glance-network:
    driver: bridge
