FROM python:3.11-alpine

WORKDIR /app

COPY extensions/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY extensions/github-scraper/github-pr-scraper.py .

EXPOSE 8087

CMD ["python", "github-pr-scraper.py"]
